language: go
go:
- '1.12.6'

services:
 - docker

jobs:
  include:
    - stage: build
      script:
        - docker --version'
        - docker build -f ./services/http/Dockerfile -t ${DOCKER_USERNAME}/go-http-server:latest .
        - docker build -f ./services/grpc/Dockerfile -t ${DOCKER_USERNAME}/go-grpc-server:latest .
        - docker tag ${DOCKER_USERNAME}/go-grpc-server:latest ${DOCKER_USERNAME}/go-grpc-server:$(git describe --long)
        - docker tag ${DOCKER_USERNAME}/go-http-server:latest ${DOCKER_USERNAME}/go-http-server:$(git describe --long)
    - stage: push
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push ${DOCKER_USERNAME}/go-grpc-server:latest && docker push ${DOCKER_USERNAME}/go-grpc-server:$(git describe --long); fi
        - if [ "$TRAVIS_BRANCH" = "master" ]; then 'docker push ${DOCKER_USERNAME}/go-http-server:latest && docker push ${DOCKER_USERNAME}/go-http-server:$(git describe --long)'; fi

stages:
   - name: build
    if: type = pull_request
      - build
   - name: push
    if: type = push AND branch = master
      - build
      - push
